# Stage 1: Build
FROM node:20 AS build

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

# Stage 2: Run
FROM node:20

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./
COPY --from=build /app/prisma ./prisma

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "dist/index.js"]
