version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend-app-prod
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
